# Generated by Django 5.0 on 2023-12-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titel',
            new_name='title',
        ),
    ]
